### ISSUE TITLE
Refers to documented API as undocumented

### ISSUE THREAD

**Issue by JosiahParry** [yinleon/inspect-element#1]
In the undocumented APIs portion of the book, the library `pyesridump` is referenced as a library that wraps undocumented REST Services. The REST API endpoints are well documented and referenced in the pyesridump documentation https://github.com/openaddresses/pyesridump

**Comment by yinleon** [comment]
Can you send me link me the documentation from ESRI?

**Comment by JosiahParry** [comment]
See feature server query capability functionality for example https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer-.htm#GUID-BC2AD141-3386-49FB-AA09-FF341145F614

**Comment by yinleon** [comment]
Thanks! I have removed `pyesridump` as an example in https://github.com/yinleon/inspect-element/commit/c839202c03a4242b40dc351124b67e63e2327564.
